about:
    access: restricted
    footnote: nll
    grain: null
    groups: null
    license: ckdbl
    processed: null
    rights: public
    source: null
    space: null
    subject: null
    summary: Dataset Summary
    tags: []
    time: null
    title: Dataset Title
contacts:
    creator:
        email: eric@civicknowledge.com
        name: Eric Busboom
        org: Civic Knowledge
        url: http://civicknowledge.com
dependencies: {}
external_documentation:
    dataset:
        description: Web page the links to the dataset description
        source: null
        title: Dataset Page
        url: http://example.com
    download:
        description: Web page that links to the source files.
        source: null
        title: Download Page
        url: http://example.com
identity:
    dataset: entities
    id: d04B
    revision: 1
    source: civicknowledge.com
    subset: census
    version: 0.0.1
names:
    fqname: civicknowledge.com-entities-census-0.0.1~d04B001
    name: civicknowledge.com-entities-census
    vid: d04B001
    vname: civicknowledge.com-entities-census-0.0.1
pipelines:
    all:
        first:
        - Select("row.component == '00' ")
    build:
        augment:
        - PassOnlyDestColumns
requirements: {}
versions: {}
