about:
    access: restricted
    footnote: null
    grain: null
    groups: []
    license: public
    processed: null
    rights: null
    source: null
    space: California
    subject: null
    summary: The physical fitness test (PFT) for students in California schools is
        the FITNESSGRAM. The main goal of the test is to help students in starting
        life-long habits of regular physical activity.
    tags: []
    time: 1999/2014
    title: Physical Fitness Test  Results
contacts:
    creator:
        email: eric@civicknowledge.com
        name: Eric Busboom
        org: Civic Knowledge
        url: http://civicknowledge.com
dependencies: {}
external_documentation:
    dataset:
        description: The physical fitness test (PFT) for students in California schools
            is the FITNESSGRAM. The main goal of the test is to help students in starting
            life-long habits of regular physical activity.
        source: null
        title: PFT Statewide Research Files
        url: http://www.cde.ca.gov/ta/tg/pf/pftresearch.asp
identity:
    btime: 1993e
    dataset: enrollment
    id: d04y
    revision: 1
    source: cde.ca.gov
    version: 0.0.1
names:
    fqname: cde.ca.gov-enrollment-1993e-0.0.1~d04y001
    name: cde.ca.gov-enrollment-1993e
    vid: d04y001
    vname: cde.ca.gov-enrollment-1993e-0.0.1
pipelines:
    build:
        augment:
        - 'Expand({ (''_year'',''_county_fips'', ''_district_code'', ''_school_code'')
            : lambda p,r,v: [ p.source.time, r[0][:2], r[0][2:7], r[0][7:] ] })'
        - bundle.LookupCDS
        first:
        - Head(400)
    schema:
        augment:
        - 'Add([''_year'',''_county_fips'', ''_district_code'', ''_school_code'']) '
        first:
        - Head(400)
    source:
        first:
        - Sample(400)
requirements: {}
versions: {}
