about:
    access: restricted
    footnote: nll
    grain: null
    groups: null
    license: ckdbl
    processed: null
    rights: public
    source: null
    space: null
    subject: null
    summary: Data provided by San Diego NBC 7 for parking tickets issued in street
        sweeping zones, and GPS positions of the street sweepers.
    tags: []
    time: null
    title: Street Sweeping Positions and Ticket
contacts:
    creator:
        email: eric@civicknowledge.com
        name: Eric Busboom
        org: Civic Knowledge
        url: http://civicknowledge.com
dependencies: {}
external_documentation:
    dataset:
        description: Web page the links to the dataset description
        source: null
        title: Dataset Page
        url: http://example.com
    download:
        description: Web page that links to the source files.
        source: null
        title: Download Page
        url: http://example.com
identity:
    dataset: streetsweep
    id: d04E
    revision: 1
    source: nbcuni.com
    version: 0.0.1
names:
    fqname: nbcuni.com-streetsweep-0.0.1~d04E001
    name: nbcuni.com-streetsweep
    vid: d04E001
    vname: nbcuni.com-streetsweep-0.0.1
pipelines:
    build-gps:
        select:
        - Select(' 1.0 < row.dblspeed < 15.0 ')
requirements: {}
versions: {}
